### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by DrGoldfire**
It always pains me to see projects that are really cool but don't work on Windows, so I thought this time I'd be the change. ;)

### CODE REVIEW

**Comment by joshlf** [comment]
You should just be able to use the mmap-alloc crate here as well; it supports Windows (I'll admit the name is a tad misleading on that front...).

**Comment by DrGoldfire** [comment]
I did see that, but I would have needed win32api anyway for the mutex, so I decided against also pulling in mmap-alloc when I really just needed one VirtualAlloc call (the same thing that mmap-alloc would end up doing).

**Comment by fitzgen** [comment]
Thanks @DrGoldfire!

It would be good to cut down on the duplication between `imp_unix` and `imp_windows`, but I don't have a solid proposal for how to do that at the moment, so we can put it on the back burner for now.

**Comment by fitzgen** [comment]
Oh! Also, if you have a moment (I'm about to go afk) updating the `wee_alloc/src/lib.rs` doc text to mention the windows support in the same place where the unix support is mentioned would be 💯 .

If not, I can do it tomorrow.

**Comment by DrGoldfire** [comment]
Submitted #20 with the doc change; no idea how I had missed that, but hey.

**Pull request merged**
